require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FaqCatesController do

  # This should return the minimal set of attributes required to create a valid
  # FaqCate. As you add validations to FaqCate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "typo" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FaqCatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all faq_cates as @faq_cates" do
      faq_cate = FaqCate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:faq_cates).should eq([faq_cate])
    end
  end

  describe "GET show" do
    it "assigns the requested faq_cate as @faq_cate" do
      faq_cate = FaqCate.create! valid_attributes
      get :show, {:id => faq_cate.to_param}, valid_session
      assigns(:faq_cate).should eq(faq_cate)
    end
  end

  describe "GET new" do
    it "assigns a new faq_cate as @faq_cate" do
      get :new, {}, valid_session
      assigns(:faq_cate).should be_a_new(FaqCate)
    end
  end

  describe "GET edit" do
    it "assigns the requested faq_cate as @faq_cate" do
      faq_cate = FaqCate.create! valid_attributes
      get :edit, {:id => faq_cate.to_param}, valid_session
      assigns(:faq_cate).should eq(faq_cate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FaqCate" do
        expect {
          post :create, {:faq_cate => valid_attributes}, valid_session
        }.to change(FaqCate, :count).by(1)
      end

      it "assigns a newly created faq_cate as @faq_cate" do
        post :create, {:faq_cate => valid_attributes}, valid_session
        assigns(:faq_cate).should be_a(FaqCate)
        assigns(:faq_cate).should be_persisted
      end

      it "redirects to the created faq_cate" do
        post :create, {:faq_cate => valid_attributes}, valid_session
        response.should redirect_to(FaqCate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved faq_cate as @faq_cate" do
        # Trigger the behavior that occurs when invalid params are submitted
        FaqCate.any_instance.stub(:save).and_return(false)
        post :create, {:faq_cate => { "typo" => "invalid value" }}, valid_session
        assigns(:faq_cate).should be_a_new(FaqCate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FaqCate.any_instance.stub(:save).and_return(false)
        post :create, {:faq_cate => { "typo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested faq_cate" do
        faq_cate = FaqCate.create! valid_attributes
        # Assuming there are no other faq_cates in the database, this
        # specifies that the FaqCate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FaqCate.any_instance.should_receive(:update).with({ "typo" => "1" })
        put :update, {:id => faq_cate.to_param, :faq_cate => { "typo" => "1" }}, valid_session
      end

      it "assigns the requested faq_cate as @faq_cate" do
        faq_cate = FaqCate.create! valid_attributes
        put :update, {:id => faq_cate.to_param, :faq_cate => valid_attributes}, valid_session
        assigns(:faq_cate).should eq(faq_cate)
      end

      it "redirects to the faq_cate" do
        faq_cate = FaqCate.create! valid_attributes
        put :update, {:id => faq_cate.to_param, :faq_cate => valid_attributes}, valid_session
        response.should redirect_to(faq_cate)
      end
    end

    describe "with invalid params" do
      it "assigns the faq_cate as @faq_cate" do
        faq_cate = FaqCate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FaqCate.any_instance.stub(:save).and_return(false)
        put :update, {:id => faq_cate.to_param, :faq_cate => { "typo" => "invalid value" }}, valid_session
        assigns(:faq_cate).should eq(faq_cate)
      end

      it "re-renders the 'edit' template" do
        faq_cate = FaqCate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FaqCate.any_instance.stub(:save).and_return(false)
        put :update, {:id => faq_cate.to_param, :faq_cate => { "typo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested faq_cate" do
      faq_cate = FaqCate.create! valid_attributes
      expect {
        delete :destroy, {:id => faq_cate.to_param}, valid_session
      }.to change(FaqCate, :count).by(-1)
    end

    it "redirects to the faq_cates list" do
      faq_cate = FaqCate.create! valid_attributes
      delete :destroy, {:id => faq_cate.to_param}, valid_session
      response.should redirect_to(faq_cates_url)
    end
  end

end
